### ISSUE TITLE
Customization of remark.js

### ISSUE THREAD

**Issue by wookayin** [kt3k/remarker#4]
Can we configure so that we can use another version of remark.js? Currently, I think it is hard-coded and bundled together (vendor/remark.js). It would be great to allow customization of scripts, not only specifying the version or path to remark.js, but also injecting custom javascript code (like css).

One another problem is that is not a minified version; viewing source is quite annoying. Moreover, I think it'd better to load remark.js as an external resource (e.g. `script src`) *by default*.

**Comment by kt3k** [comment]
Thanks for the feedback!

> Currently, I think it is hard-coded and bundled together (vendor/remark.js).

Yes, that's hard coded now.

> It would be great to allow customization of scripts, not only specifying the version or path to remark.js, but also injecting custom javascript code (like css).

I agree that injecting scripts could be useful in some use cases. I'll work on it soon.

> One another problem is that is not a minified version; viewing source is quite annoying. Moreover, I think it'd better to load remark.js as an external resource (e.g. script src) by default.

OK. I see that if soneone try to hack on the remarker output html, the current bundle is not comfortable to work on. I'll try to make the script external.

Thanks for trying remarker!

**Comment by kt3k** [comment]
@wookayin 
I added `script` option ( refs: https://github.com/kt3k/remarker/commit/751f707babae36d53bdc17f691018d3068f1f6b9 ) and remark.js path configurable ( refs: https://github.com/kt3k/remarker/commit/73a395795588cfbb3b369ad85c8ac47fbe0d317a ).

Could you check the behavior when you have time?

**Comment by wookayin** [comment]
Great! They work well. Thanks for the support :)
