### ISSUE TITLE
Program line argument to specify the source

### ISSUE THREAD

**Issue by cansik** [kt3k/remarker#7]
It would be great to have a program line argument to pass the **slide markdown** file to the remarker:

```bash
npx remarker --source myslide.md
```

Because I have multiple slides at the moment in the same folder and would like to leave the name as it is.

**Comment by kt3k** [comment]
@cansik Thanks for the feedback. I added `--source` option to the cli at v1.6.0. Please check the latest version!

**Comment by cansik** [comment]
It seems that now remarker is serve two times and blocking itself:

```bash
npx remarker -s Lernziele.md
berber [19:04:58] serving
berber [19:04:58] Reading: slides.md
berber [19:04:58] Reading: /Users/cansik/.npm/_npx/49227/lib/node_modules/remarker/vendor/remark.js
berber [19:04:58] Reading: assets/**/*.*
berber [19:04:58] serving
berber [19:04:58] Reading: slides.md
berber [19:04:58] Reading: /Users/cansik/node_modules/remarker/vendor/remark.js
berber [19:04:58] Reading: assets/**/*.*
berber [19:04:58] Server started at: http://localhost:6275/
berber [19:04:58] See debug info at: http://localhost:6275/__remarker__
berber [19:04:58] Error: The port number 6275 is already in use
```

**Comment by kt3k** [comment]
The above doesn't happen on my side. It seems very strange.

As far as I read the above log messages, remarker started from 2 places `/Users/cansik/node_modules/remarker/` and `/Users/cansik/.npm/_npx/49227/lib/node_modules/remarker/`. I guess npx is doing something wrong. Could you check about npx or just avoid using it and invoke remarker directly?

BTW I found at least one error on option parsing (`-s` handling was wrong https://github.com/kt3k/remarker/commit/66d9212ded92fdc74a512897f178ee5ee9b0133c). I fixed it and released as v1.6.1.

**Comment by kt3k** [comment]
Sorry. npx wasn't a problem. When I installed remarker both locally and globally and invoked global version, then the above behavior happpened. So using the local version explicitly or removing the global version would solve the problem.

**Comment by cansik** [comment]
Yes, removing one version helped! Great and thank you for the help 👍
