### ISSUE TITLE
no way to supply single files as assets

### ISSUE THREAD

**Issue by igalic** [kt3k/remarker#8]
I'd like to supply a single file as asset, such as a favicion.ico, however, the `asset` array assumes all elements are directories.

Is there any way to fix that?
because even if i "manually" copy the file in a script line:

```json
{
  "dependencies": {
    "remarker": "^1.6.2"
  },
  "scripts": {
    "build": "remarker build; cp favicon.ico build/",
    "serve": "remarker serve",
    "clean": "rm -rf build"
  }
}
```

it won't work, because the `assets` array is also used to build what's being `serve`d.

**Comment by kt3k** [comment]
I added type check for assets entries and release it as `v1.7.1`. I think it solves your problem. Please check the latest version.

An example for favicon use case is available at https://github.com/kt3k/remarker/tree/master/examples/favicon

**Comment by igalic** [comment]
perfect! thank you so much!
