### ISSUE TITLE
Feature request: live reload for development

### ISSUE THREAD

**Issue by fiznool** [kt3k/remarker#9]
It's a bit of a pain to keep having to Cmd-R in the browser whenever a file has been changed. Is there any way to enable LiveReload so that the browser refreshes when the slide content is saved?

**Comment by kt3k** [comment]
Thanks for the request!

Currently remarker doesn't have that feature, but it seems possible with the combination of [gulp-livereload](https://github.com/vohof/gulp-livereload) and [connect-livereload](https://github.com/intesso/connect-livereload). I'll try that next week.

**Comment by kt3k** [comment]
Added livereloading at https://github.com/kt3k/remarker/commit/8aed7c32a6a9a26c068b9ea5da407e213a748812.

Released it as v1.8.0.

**Comment by fiznool** [comment]
Works beautifully and is a huge timesaver. Thanks so much! 🙏
